BasedOnStyle: GNU

AlignEscapedNewlines: LeftWithLastLine
AllowShortIfStatementsOnASingleLine: AllIfsAndElse
AllowShortLoopsOnASingleLine: true
BinPackArguments: false
BraceWrapping:
  AfterControlStatement: Always
  AfterFunction: true
  BeforeElse: true
BreakBeforeBraces: Custom
ColumnLimit: 160
Cpp11BracedListStyle: true
IndentPPDirectives: AfterHash
IndentWidth: 4
PPIndentWidth: 2
SortIncludes: Never
SpaceBeforeParens: Custom
SpaceBeforeParensOptions:
  AfterControlStatements: true
  AfterFunctionDefinitionName: false
